framework:
    messenger:

        failure_transport: failed

        transports:
            async:
                dsn:  "%env(MESSENGER_TRANSPORT_DSN)%"
            failed:
                dsn: "doctrine://default?queue_name=failed"

        routing:
            'App\Message\Notification': async
